spring:
 application:
   name: distributor
 data:
   mongodb:
     database: distributormovie
     host: 127.0.0.1
     port: "27017"
     uri: mongodb://127.0.0.1/distributormovie
     username: ""

eureka:
 client:
   service-url:
     defaultZone: http://127.0.0.1:9083/eureka
   register-with-eureka: "true"
   fetch-registry: "true"
management:
 endpoints:
  web:
   exposure:
    include: "*"
