eureka:
 client:
   register-with-eureka: "false"
   fetch-registry: "false"
spring:
 application:
   name: EurekaServer
logging:
 level:
   com:
     netflix:
       eureka: "OFF"
       discovery: "OFF"
management:
 endpoints:
   web:
     exposure:
       include: '*'
