--- 
eureka: 
  client: 
    fetch-registry: "true"
    register-with-eureka: "true"
    serviceUrl: 
      defaultZone: "http://127.0.0.1:9083/eureka/"
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring: 
  application: 
    name: payment
  data: 
    mongodb: 
      database: payment
      host: 127.0.0.1
      port: "27017"
      uri: "mongodb://127.0.0.1/payment"
      username: ""
bootstrap-id : 127.0.0.1:9092
