spring:
 data:
   neo4j:
     username: neo4j
     password: root123
     uri: bolt://127.0.0.1

 application:
   name: recommendation-ms
eureka:
 client:
   register-with-eureka: "true"
   fetch-registry: "true"
   serviceUrl:
     defaultZone: http://127.0.0.1:9083/eureka/
management:
 endpoints:
  web:
   exposure:
    include: "*"
bootstrap-id : 127.0.0.1:9092
