spring:
 application:
   name: movie-search
 cloud:
   config:
     uri: http://127.0.0.1:9084
 data:
   mongodb:
     database: moviedb
     host: localhost
     port: "27017"
     uri: mongodb://127.0.0.1/moviedb
     username: ""

eureka:
 client:
   register-with-eureka: "true"
   fetch-registry: "true"
   serviceUrl:
     defaultZone: http://127.0.0.1:9083/eureka/
management:
 endpoints:
  web:
   exposure:
    include: "*"
bootstrap-id : 127.0.0.1:9092
