spring:
 application:
   name: theatre
 data:
   mongodb:
     database: theatre
     host: 127.0.0.1
     port: "27017"
     uri: mongodb://127.0.0.1/theatre
     username: ""
eureka:
 client:
   register-with-eureka: "true"
   fetch-registry: "true"
   service-url:
     defaultZone: http://127.0.0.1:9083/eureka
management:
 endpoints:
  web:
   exposure:
    include: "*"
bootstrap-id : 127.0.0.1:9092
