
spring:
  data:
    mongodb:
      database: userdb
      host: 127.0.0.1
      port: "27017"
      uri: mongodb://127.0.0.1/userdb
      username: ""
  application:
    name: UserProfile

eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    serviceUrl:
      defaultZone: http://127.0.0.1:9083/eureka/
management:
 endpoints:
  web:
   exposure:
    include: "*"
bootstrap-id : 127.0.0.1:9092

